# Generated by Django 4.1.3 on 2022-11-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter name', max_length=500, null=True, verbose_name='Bot User')),
                ('telegram', models.CharField(help_text='Enter telegram id', max_length=20, unique=True, verbose_name='Telegram ID')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot User ',
                'verbose_name_plural': 'Bot Users ',
            },
        ),
    ]
